name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg@latest
        
      - name: Verify pkg installation
        run: pkg --version
        
      - name: Build binary (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:windows
        
      - name: Build binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        
      - name: Build binary (macOS Intel)
        if: matrix.os == 'macos-latest'
        run: npm run build:macos
        
      - name: Build binary (macOS ARM64)
        if: matrix.os == 'macos-latest'
        run: npm run build:macos-arm64
        
      - name: Copy cheats and config (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p build
          copy cheats.js build\cheats.js
          copy "src\config\config.custom.example.js" "build\config.custom.example.js"
        shell: cmd
        
      - name: Copy cheats and config (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p build
          cp cheats.js build/cheats.js
          cp src/config/config.custom.example.js build/config.custom.example.js
        shell: bash
        
      - name: Copy cheats and config (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p build
          cp cheats.js build/cheats.js
          cp src/config/config.custom.example.js build/config.custom.example.js
        shell: bash
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IdleCI-${{ matrix.os }}
          path: |
            build/IdleCI-*
            build/cheats.js
            build/config.custom.example.js
          retention-days: 30

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: IdleCI-windows-latest
          path: build/windows
          
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: IdleCI-ubuntu-latest
          path: build/linux
          
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: IdleCI-macos-latest
          path: build/macos
          
      - name: Create release packages
        run: |
          # Create Windows package
          cd build/windows
          zip -r ../../IdleCI-Windows-x64.zip IdleCI-windows-x64.exe cheats.js config.custom.example.js
          cd ../..
          
          # Create Linux package
          cd build/linux
          zip -r ../../IdleCI-Linux-x64.zip IdleCI-linux-x64 cheats.js config.custom.example.js
          cd ../..
          
          # Create macOS Intel package
          cd build/macos
          zip -r ../../IdleCI-macOS-x64.zip IdleCI-macos-x64 cheats.js config.custom.example.js
          cd ../..
          
          # Create macOS ARM64 package
          cd build/macos
          zip -r ../../IdleCI-macOS-arm64.zip IdleCI-macos-arm64 cheats.js config.custom.example.js
          cd ../..
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            IdleCI-Windows-x64.zip
            IdleCI-Linux-x64.zip
            IdleCI-macOS-x64.zip
            IdleCI-macOS-arm64.zip
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 