name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg@latest
        
      - name: Verify pkg installation
        run: pkg --version
        
      - name: Build binary (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:windows
        
      - name: Build binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        
      - name: Copy cheats and config (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p build
          copy cheats.js build\cheats.js
          copy "src\config\config.custom.example.js" "build\config.custom.example.js"
        shell: cmd
        
      - name: Copy cheats and config (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p build
          cp cheats.js build/cheats.js
          cp src/config/config.custom.example.js build/config.custom.example.js
        shell: bash
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IdleCI-${{ matrix.os }}
          path: |
            build/IdleCI-*
            build/cheats.js
            build/config.custom.example.js
          retention-days: 30

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: IdleCI-windows-latest
          path: build/windows
          
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: IdleCI-ubuntu-latest
          path: build/linux
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/IdleCI-windows-x64.exe
            build/windows/cheats.js
            build/windows/config.custom.example.js
            build/linux/IdleCI-linux-x64
            build/linux/cheats.js
            build/linux/config.custom.example.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 